### ISSUE TITLE
https://tsed.io/tutorials/socket-io.html#socket-service

### ISSUE THREAD

**Issue by muradmalik777** [Romakita/romakita#1]
I am trying to implement websockets with TSED but I am not able to make it work. 
Here are my socket.io configurations
`socketIO: {
        path: "/myfii-channel",
        cors: { origin: "*", credentials: true },
        adapter: createAdapter(pubClient, subClient),
        serveClient: false,
        httpCompression: false,
        allowUpgrades: true,
        transports: ["websocket", "polling"],
        maxHttpBufferSize: 1000000,
        perMessageDeflate: {
            threshold: 2048,
            zlibDeflateOptions: {
                chunkSize: 8 * 1024
            },
            zlibInflateOptions: {
                windowBits: 14,
                memLevel: 7
            },
            clientNoContextTakeover: true,
            serverNoContextTakeover: true,
            serverMaxWindowBits: 10,
            concurrencyLimit: 10
        }
    },`
    I am trying to connect from a simple html file. It shows that the connection is established but I am not receiving any events emitted from either side i-e server/client.
    any help would be greatly appreciated @Romakita

**Comment by muradmalik777** [comment]
Here is the code for my socketService
`
import {
    IO,
    Nsp,
    Socket,
    SocketService,
    SocketUseBefore,
    SocketUseAfter,
    Emit,
    Input,
    Args,
    Namespace
} from "@tsed/socketio";
import * as SocketIO from "socket.io";
// import { codeToMessage } from "../helpers/responseMessages";
// import { INVALID_IDENTITY } from "../helpers/responseMessages";
import { UseBeforeSocketMiddleware, ErrorHandlerSocketMiddleware } from "../middlewares/UserAuthMiddleware";

@SocketService("/user")
export class UserDataSocketService {
    @Nsp nsp: SocketIO.Namespace;

    public clients: Map<string, SocketIO.Socket> = new Map();

    constructor(@IO private io: SocketIO.Server) {}

    $onConnection(@Socket socket: SocketIO.Socket) {
        console.log("111111111");
        socket.emit("hello", "murad");
        // const identityId = socket.handshake.query.identityId as string;
        // if (!identityId) socket.emit("error", { message: codeToMessage[MISSING_IDENTITY] });
        // this.identityService
        //     .findByIdentityId(identityId)
        //     .then(() => {
        //         this.clients.set(identityId, socket);
        //         console.log("=====   CONNECTED A CLIENT   =====");
        //         console.log(`===== SOCKET ID ${socket.id} =====`);
        //         socket.emit("Hello There!");
        //     })
        //     .catch(() => {
        //         socket.emit("error", { message: codeToMessage[INVALID_IDENTITY] });
        //     });
    }

    $onDisconnect(@Socket socket: SocketIO.Socket) {
        socket.emit("disconnect", "Bye Bye!");
    }

    @Input("hello")
    @Emit("world")
    @SocketUseBefore(UseBeforeSocketMiddleware)
    @SocketUseAfter(ErrorHandlerSocketMiddleware)
    myMethod(@Args(0) userName: string, @Socket socket: Socket, @Namespace nsp: Namespace) {
        console.log(userName, nsp.name);
        socket.emit("world", "murad");
    }

    public async emitAuthorizationRequest(identityId: string) {
        const socket = this.clients.get(identityId);
        if (!socket) return;
        socket.emit("authorizationRequest", { user: "murad" });
    }
}

`

**Comment by muradmalik777** [comment]
this is my client
<script>
        const socket = io("ws://localhost:4000", { path: "/myfii-channel/user" });
        console.log("check 1", socket.connected);
        socket.on("connect", () => {
            console.log("connected to server");
            socket.emit("hello", "world");
            console.log("check 1", socket.connected);
        });

        socket.on("world", () => {
            console.log("hello event received");
        });

        // handle the event sent with socket.send()
        socket.on("disconnect", (data) => {
            console.log("disconnected");
        });
    </script>`
`

**Comment by muradmalik777** [comment]
<img width="189" alt="Screenshot 2022-09-13 at 2 29 04 AM" src="https://user-images.githubusercontent.com/42974204/189761976-4587e2b6-707f-4773-8cb4-77523d938c27.png">
and the handshake seems to be established

**Comment by muradmalik777** [comment]
Do I need to inject this socket service somewhere? I noticed some weird behavious actually. The namespace documentation at the command line is only generated when I inject my socket service in any controller. Socket server is only initialized when I attach the **before**, **after** hooks. Seems like there is something not working properly.

**Comment by muradmalik777** [comment]
and I get this error sometimes too.

Error: write EPIPE
    at process.target._send (node:internal/child_process:867:20)
    at process.target.send (node:internal/child_process:740:19)
    at Object.exports.send (/Users/murad/work/myfii-api/node_modules/ts-node-dev/lib/ipc.js:17:14)
    at /Users/murad/work/myfii-api/node_modules/ts-node-dev/lib/wrap.js:88:9
    at Object.nodeDevHook [as .node] (/Users/murad/work/myfii-api/node_modules/ts-node-dev/lib/hook.js:61:17)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at DefaultLibraryLoader.loadLibrary (/Users/murad/work/myfii-api/node_modules/@prisma/client/runtime/index.js:25785:29)`
`

**Comment by Romakita** [comment]
Hello @muradmalik777 

this is not the right place to open issue.
please open it on tsed repository.

and please take a time to format correctly your code example using three back tick for a code block ;)

see you
Romain
