### ISSUE TITLE
Serverless tsed (lambda) example repo?

### ISSUE THREAD

**Issue by jandnil** [Romakita/romakita#2]
Hi!

I saw the TS.ED support for aws serverless development and it looked interesting and I just wanted to check if there are any good example repo or example solution showcasing usage besides the tutorial?
Many thanks for any pointers and have a great day

**Comment by Romakita** [comment]
Hello @jandnil 
All of your needs is here: https://tsed.io/tutorials/serverless.html#configuration a

You can look on this directory to retrieve some piece of code and configuration for a serverless project:
https://github.com/tsedio/tsed/blob/production/packages/platform/platform-serverless-http/test/integration/aws-basic

Next time, it'll preferable to open a discussion on  this repository: https://github.com/orgs/tsedio/discussions ;)

See you
